apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "REPLACE_ME",
          "password": "REPLACE_ME",
          "email": "REPLACE_ME",
          "auth": "REPLACE_ME_BASE64_USERNAME_COLON_TOKEN"
        }
      }
    }
