apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nexus-gateway
  namespace: nginx-gateway  # Namespace central para o controller e o gateway
  annotations:
    oci-network-load-balancer.oraclecloud.com/external-ip-only: "true"
    external-dns.alpha.kubernetes.io/hostname: "*.nexusplatform.com.br,nexusplatform.com.br"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/target: "132.226.245.136"
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: "*.nexusplatform.com.br"
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    port: 443
    protocol: HTTPS
    hostname: "*.nexusplatform.com.br"
    tls:
      mode: Terminate
      certificateRefs:
      - name: wildcard-tls-secret
        namespace: nginx-gateway
    allowedRoutes:
      namespaces:
        from: All
