apiVersion: v1
data:
  ALGORITHM: SFMyNTY=
  DATABASE_URL: bXlzcWwrcHlteXNxbDovL3BsdXJpb3JhbF91c2VyOlVzZXJfcGFzc3dvcmRfc2VndXJhITFAMTAuMC44MS4yMDQ6MzMwNi9wbHVyaW9yYWxfbmRi
  DB_PASSWORD: VXNlcl9wYXNzd29yZF9zZWd1cmEhMQ==
  DB_USER: dGVzdGVfdXNlcg==
  SECRET_KEY: dW1hLWNoYXZlLXNlY3JldGEtbXVpdG8tZm9ydGUtZS1kaWZpY2lsLWRlLWFkaXZpbmhhcg==
kind: Secret
metadata:
  name: nexus-db-credentials
type: Opaque
