apiVersion: v1
kind: Secret
metadata:
  name: nexus-campaign-api-secret
type: Opaque
data:
  # Substituir pelos valores reais no overlay
  DATABASE_URL: bXlzcWwrcHlteXNxbDovL3VzZXI6cGFzc0Bsb2NhbGhvc3Q6MzMwNi9uZXh1c19jYW1wYWlnbg==
  SECRET_KEY: Y2hhbmdlX3RoaXNfc2VjcmV0X2tleV82NF9jaGFyc19wYWRkaW5nX2hlcmVfZm9yX2p3dF9zaWc=
  REDIS_URL: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OS8w
  NEXUS_CI_TOKEN: Y2hhbmdlX21lX25leHVzX2NpX3Rva2Vu
  NEXUS_CORE_WEBHOOK_SECRET: Y2hhbmdlX3RoaXNfd2ViaG9va19zZWNyZXQ=
