apiVersion: v1
kind: Service
metadata:
  name: marquez
  namespace: marquez
  labels:
    app.kubernetes.io/name: marquez
    app.kubernetes.io/component: marquez
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: marquez
    app.kubernetes.io/component: marquez
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: http-admin
      port: 5001
      targetPort: http-admin
      protocol: TCP
