apiVersion: v1
kind: Service
metadata:
  name: athena-webapp-service
  labels:
    app: athena-webapp
spec:
  type: ClusterIP
  selector:
    app: athena-webapp
  ports:
  - name: http
    port: 80
    targetPort: 80
