apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nexus-webapp-tls
  namespace: nexus-webapp
spec:
  secretName: migration-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - migration.nexusplatform.com.br
