apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redpanda-tech-tls
  namespace: redpanda
spec:
  secretName: redpanda-tech-tls-secret
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: tech.nexusplatform.com.br
  dnsNames:
    - tech.nexusplatform.com.br
    - "*.tech.nexusplatform.com.br"
