# Strategic merge patch — K3d local-first
# 1 broker: evita problema de podAntiAffinity em cluster single-node
# TLS desabilitado para simplificar o dev local
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  clusterSpec:
    external:
      domain: ""
    statefulset:
      replicas: 1
      initContainers:
        setDataDirOwnership:
          enabled: true
    storage:
      persistentVolume:
        size: 5Gi
    tls:
      enabled: false
