---
# Source: langflow-ide/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: langflow-ide-postgresql
  namespace: "langflow"
  labels:
    app.kubernetes.io/instance: langflow-ide
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.4.0
    helm.sh/chart: postgresql-15.5.38
type: Opaque
data:
  postgres-password: "YklWc3FIbVpZcg=="
  password: "bGFuZ2Zsb3ctcG9zdGdyZXM="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
---
apiVersion: v1
kind: Secret
metadata:
  name: langflow-secret
type: Opaque
stringData:
  # O Kubernetes irá codificar estes valores em Base64 automaticamente
  #LANGFLOW_DATABASE_URL: "postgresql://user:password@localhost:5432/langflow"
  LANGFLOW_DATABASE_URL: "sqlite:////data/langflow.db"
  LANGFLOW_SECRET_KEY: "somesecretkey"
  LANGFLOW_SUPERUSER: "adminuser"
  LANGFLOW_SUPERUSER_PASSWORD: "adminpass"
