apiVersion: v1
data:
  ALGORITHM: SFMyNTY=
  DATABASE_URL: bXlzcWwrcHlteXNxbDovL3Rlc3RlX3VzZXI6VXNlcl9wYXNzd29yZF9zZWd1cmEhMUAxMC4wLjgxLjIwNDozMzA2L3Rlc3RlX25kYg==
  DB_PASSWORD: VXNlcl9wYXNzd29yZF9zZWd1cmEhMQ==
  DB_USER: dGVzdGVfdXNlcg==
  SECRET_KEY: dW1hLWNoYXZlLXNlY3JldGEtbXVpdG8tZm9ydGUtZS1kaWZpY2lsLWRlLWFkaXZpbmhhcg==
  STRIPE_API_KEY: c2tfdGVzdF81MVQyVncyUXNObUNpQWpHSnliNWx1OE50V2xNSzV2bmFpa0h0M3pFdndHRXZrc3dVOE4wVkJRMlFXWjNxZXJNZUlpakN1ZG1WSFVoSHoySGN5SnEzYUpVYTAwTWJFOTJyTlo=
  STRIPE_WEBHOOK_SECRET: d2hzZWNfX18=
kind: Secret
metadata:
  name: nexus-db-credentials
type: Opaque
