apiVersion: v1
kind: Service
metadata:
  name: athena-api-service
  labels:
    app: athena-api
spec:
  type: ClusterIP
  selector:
    app: athena-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
