apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redpanda-tls
  namespace: redpanda
spec:
  secretName: redpanda-tls-secret
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: nexusplatform.com.br
  dnsNames:
    - nexusplatform.com.br
    - "*.nexusplatform.com.br"
