---
apiVersion: v1
data:
  apiKey: RWViWTFfYU43V0F6M2w4bThZR0FFUjBXQW5pemFsWmhQWVlQdFRjYQ==
  email: aGFyb2xkb3Byb2VuY2FAZ21haWwuY29t
kind: Secret
metadata:
  name: cloudflare-api-key
  namespace: external-dns
type: Opaque
