apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-api-config
data:
  FRONTEND_URL: "https://placeholder.nexusplatform.com.br"
  CORS_ORIGINS: "https://placeholder.nexusplatform.com.br,https://placeholder-api.nexusplatform.com.br,http://localhost:5173"
  NEXUS_CEP_URL: "http://nexus-cep-service.nexus-cep.svc.cluster.local:80"
  SMTP_HOST: "smtp.email.sa-saopaulo-1.oci.oraclecloud.com"
  SMTP_PORT: "587"
  EMAILS_FROM_EMAIL: "noreply@nexusplatform.com.br"
  EMAILS_FROM_NAME: "Nexus Platform"
