apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus-prod

resources:
- ../../../bases/nexus-campaign-api
- namespace.yaml
- hpa.yaml

patches:
- path: deployment.yaml
- path: configmap.yaml
- path: secret.yaml
- path: httproute.yaml
