apiVersion: v1
kind: Secret
metadata:
  name: nexus-db-credentials
type: Opaque
data:
  ALGORITHM: SFMyNTY=
  # mysql+pymysql://nexusone_user:User_password_segura!1@10.0.81.204:3306/nexusone_ndb
  DATABASE_URL: bXlzcWwrcHlteXNxbDovL25leHVzb25lX3VzZXI6VXNlcl9wYXNzd29yZF9zZWd1cmEhMUAxMC4wLjgxLjIwNDozMzA2L25leHVzb25lX25kYg==
  DB_PASSWORD: VXNlcl9wYXNzd29yZF9zZWd1cmEhMQ==
  DB_USER: bmV4dXNvbmVfdXNlcg==
  SECRET_KEY: dW1hLWNoYXZlLXNlY3JldGEtbXVpdG8tZm9ydGUtZS1kaWZpY2lsLWRlLWFkaXZpbmhhcg==