apiVersion: v1
kind: Secret
metadata:
  name: meu-secret-banco
  namespace: debezium-platform
type: Opaque
data:
  # SUBSTITUA pelos valores reais codificados em base64
  # echo -n "usuario" | base64
  username: ZGViZXppdW0=
  # echo -n "senha-segura" | base64
  password: ZGViZXppdW0=
