---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJncnUub2Npci5pbyI6eyJ1c2VybmFtZSI6ImdyOWFqemlkbGNmZS9zaW5hcHNlc29sdWNvZXN0ZWNub2xvZ2ljYXNAZ21haWwuY29tIiwicGFzc3dvcmQiOiJQUGd0ZmpMOU1dcks5KUpPOmNzVCIsImVtYWlsIjoic2luYXBzZXNvbHVjb2VzdGVjbm9sb2dpY2FzQGdtYWlsLmNvbSIsImF1dGgiOiJaM0k1WVdwNmFXUnNZMlpsTDNOcGJtRndjMlZ6YjJ4MVkyOWxjM1JsWTI1dmJHOW5hV05oYzBCbmJXRnBiQzVqYjIwNlVGQm5kR1pxVERsTlhYSkxPU2xLVHpwamMxUT0ifX19
kind: Secret
metadata:
  name: ocir-secret
type: kubernetes.io/dockerconfigjson