apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # URL de Produção do Let's Encrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    # Substitua pelo seu email real para receber alertas de expiração
    email: haroldoproenca@gmail.com
    # Nome do secret onde o Cert-Manager guardará a chave privada da conta ACME
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - selector: {}
      dns01:
        cloudflare:
          email: haroldoproenca@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stg
  namespace: cert-manager
spec:
  acme:
    # URL de Produção do Let's Encrypt
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Substitua pelo seu email real para receber alertas de expiração
    email: haroldoproenca@gmail.com
    # Nome do secret onde o Cert-Manager guardará a chave privada da conta ACME
    privateKeySecretRef:
      name: letsencrypt-stg-account-key
    solvers:
    - selector: {}
      dns01:
        cloudflare:
          email: haroldoproenca@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token