apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  # Gerar com:
  # kubectl create secret docker-registry ghcr-secret \
  #   --docker-server=ghcr.io \
  #   --docker-username=<github-user> \
  #   --docker-password=<github-pat> \
  #   --namespace=nexus-prod --dry-run=client -o yaml
  .dockerconfigjson: REPLACE_WITH_BASE64_DOCKERCONFIG
