apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-cert-ref
  namespace: nexus-api
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: nexus-webapp
  to:
  - group: ""
    kind: Secret
