apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-campaign-api-config
data:
  CORS_ORIGINS: "http://campaign.nexusplatform.com.br,http://localhost:5173"
  ENVIRONMENT: "local"
  AUTO_CREATE_SCHEMA: "true"
  LOG_LEVEL: "DEBUG"
