apiVersion: v1
data:
  ALGORITHM: SFMyNTY=
  DATABASE_URL: bXlzcWwrcHlteXNxbDovL2FtYWJsZV91c2VyOlVzZXJfcGFzc3dvcmRfc2VndXJhITFAMTAuMC44MS4yMDQ6MzMwNi9hbWFibGVfbmRi
  DB_PASSWORD: VXNlcl9wYXNzd29yZF9zZWd1cmEhMQ==
  DB_USER: dGVzdGVfdXNlcg==
  SECRET_KEY: dW1hLWNoYXZlLXNlY3JldGEtbXVpdG8tZm9ydGUtZS1kaWZpY2lsLWRlLWFkaXZpbmhhcg==
kind: Secret
metadata:
  name: nexus-db-credentials
type: Opaque
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJncnUub2Npci5pbyI6eyJ1c2VybmFtZSI6ImdyOWFqemlkbGNmZS9zaW5hcHNlc29sdWNvZXN0ZWNub2xvZ2ljYXNAZ21haWwuY29tIiwicGFzc3dvcmQiOiJQUGd0ZmpMOU1dcks5KUpPOmNzVCIsImVtYWlsIjoic2luYXBzZXNvbHVjb2VzdGVjbm9sb2dpY2FzQGdtYWlsLmNvbSIsImF1dGgiOiJaM0k1WVdwNmFXUnNZMlpsTDNOcGJtRndjMlZ6YjJ4MVkyOWxjM1JsWTI1dmJHOW5hV05oYzBCbmJXRnBiQzVqYjIwNlVGQm5kR1pxVERsTlhYSkxPU2xLVHpwamMxUT0ifX19
kind: Secret
metadata:
  name: ocir-secret
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiaGFyb2xkb3Byb2VuY2EiLCJwYXNzd29yZCI6ImdocF9TZVI0UDQ4dm9USGxoYkkwcHVHUVl2WlAySGJSSmEyYjBLOHAiLCJlbWFpbCI6Imhhcm9sZG9wcm9lbmNhQGdtYWlsLmNvbSIsImF1dGgiOiJhR0Z5YjJ4a2IzQnliMlZ1WTJFNloyaHdYMU5sVWpSUU5EaDJiMVJJYkdoaVNUQndkVWRSV1haYVVESklZbEpLWVRKaU1FczRjQT09In19fQ==
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
