---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        # --- ATENÇÃO: Utilize Kubernetes Secrets para dados sensíveis em produção. ---
        - name: MYSQL_ROOT_PASSWORD
          value: "root_password_segura"
        - name: MYSQL_DATABASE
          value: "teste_ndb"
        - name: MYSQL_USER
          value: "teste_user"
        - name: MYSQL_PASSWORD
          value: "user_password_segura"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc