apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tech-nexus-cert
  namespace: nginx-gateway
spec:
  secretName: wildcard-tech-tls-secret
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - "*.tech.nexusplatform.com.br"
