apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: risingwave

resources:
  - ../../../bases/risingwave/0.15
  - risingwave-sources-job.yaml
  - dashboard-service.yaml
  - httproute-dashboard.yaml
