apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: debezium-platform

resources:
  - namespace.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - role.yaml
  - rolebinding.yaml
  - service-account.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
