---
# Source: debezium-platform/charts/debezium-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: debezium-operator
    app.kubernetes.io/version: 3.2.0-beta1
  name: debezium-operator
---
# Source: debezium-platform/templates/conductor-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conductor-service-account