apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-msg-api-deployment
spec:
  template:
    spec:
      containers:
      - name: nexus-msg-api-container
        image: nexus-msg-api:v0.1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: gateway-data
          mountPath: /data
      - name: nexus-msg-worker-container
        image: nexus-msg-api:v0.1.0
        imagePullPolicy: IfNotPresent
        command: ["python", "-m", "app.worker"]
        envFrom:
        - configMapRef:
            name: nexus-msg-api-config
        - secretRef:
            name: nexus-msg-api-secrets
        volumeMounts:
        - name: gateway-data
          mountPath: /data
      volumes:
      - name: gateway-data
        emptyDir: {}
