apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus-msg-api

resources:
- ../../../../bases/nexus-msg-api
- httproute.yaml

patches:
- path: configmap.yaml
- path: secret.yaml
- path: deployment.yaml

