apiVersion: v1
kind: Secret
metadata:
  name: nexus-msg-api-secrets
type: Opaque
stringData:
  DATABASE_URL: "sqlite:////tmp/nexus_msg_gateway.db"
  META_APP_ID: "909802928132362"
  META_APP_SECRET: ""
  META_EMBEDDED_SIGNUP_CONFIG_ID: ""
  WHATSAPP_WEBHOOK_VERIFY_TOKEN: "nexusplatformtokenmessages2026"
  WHATSAPP_TEST_ACCESS_TOKEN: "EAAM7dgBY0QoBRZCVpDdq0wEb0vFklPgX1FFxgL5ocOahCTcgJncNeEkb8seQgJ24koegY49hWn7sLGsPtiFYpJ1WpeoJXQwFzrtMVzXO2Q5iyS2smfbFFTempcPZAIcJeHem7AIz2yxpbXeZAZAAXZCiDactzZAix4AiX5Fiwqds0VH7sZA0CcHytP3NqPTwUYv6i0cr0160DnOJoVxpoMJhn7L2khGZCABDdEehDaNxbVf8L5sm4e0Wrmk75lLFOQmhGEbS2hFq7cdnTaxwRIe2OBnwYSrSsZBOTn3qJLZAQZD"
  ADMIN_API_KEY: "change-me-local"
