---
apiVersion: v1
kind: Namespace
metadata:
  name: nexus-backup
---
# 1. Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-sa
  namespace: nexus-backup
  annotations:
    oci.oraclecloud.com/oci-use-workload-identity: "true"
---
# 2. ClusterRole (Permissão para ler tudo em todos os namespaces)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backup-read-all
rules:
  # Permissão para listar Namespaces
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  # Permissão para ler recursos dentro dos namespaces (para fazer o dump yaml)
  - apiGroups: ["", "apps", "networking.k8s.io", "batch", "extensions"]
    resources: 
      - "pods"
      - "services"
      - "configmaps"
      - "secrets"
      - "persistentvolumeclaims"
      - "deployments"
      - "statefulsets"
      - "ingresses"
      - "jobs"
      - "cronjobs"
    verbs: ["get", "list"]
---
# 3. ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backup-sa-binding
subjects:
- kind: ServiceAccount
  name: backup-sa
  namespace: nexus-backup
roleRef:
  kind: ClusterRole
  name: backup-read-all
  apiGroup: rbac.authorization.k8s.io
---
# 4. CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nexus-full-backup
  namespace: nexus-backup
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          imagePullSecrets:
            - name: ghcr-secret
          serviceAccountName: backup-sa
          containers:
          - name: backup-worker
            image: ghcr.io/synapsehealthtech/nexus-backup:v0.0.9
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: backup-config
            env:
            - name: BACKUP_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: backup-db-secret
                  key: password
            # OCI Workload Identity (manual — webhook nem sempre injeta em CronJobs)
            - name: OCI_RESOURCE_PRINCIPAL_VERSION
              value: "2.2"
            - name: OCI_RESOURCE_PRINCIPAL_REGION
              value: "sa-saopaulo-1"

            #resources:
            #  requests:
            #    memory: "512Mi"
            #    cpu: "500m"
            #  limits:
            #    memory: "2Gi"
            #    cpu: "2000m"

            volumeMounts:
            - name: temp
              mountPath: /tmp
            - name: oci-token
              mountPath: /var/run/secrets/oci
              readOnly: true
          
          restartPolicy: OnFailure
          volumes:
          - name: temp
            emptyDir: {}
          - name: oci-token
            projected:
              sources:
              - serviceAccountToken:
                  audience: oci
                  expirationSeconds: 7200
                  path: token