apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marquez

resources:
- ../../../bases/marquez/0.50
- secret.yaml
- httproute.yaml

patches:
- path: deployment-api-patch.yaml
