---
apiVersion: v1
kind: Service
metadata:
  name: nexus-agenticops-api-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nexus-agenticops-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
