apiVersion: v1
kind: Service
metadata:
  name: cubestore-router
  labels:
    app: cubestore-router
spec:
  type: ClusterIP
  selector:
    app: cubestore-router
  ports:
    - name: meta
      port: 9999
      targetPort: 9999
      protocol: TCP
    - name: http
      port: 3030
      targetPort: 3030
      protocol: TCP
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
