apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: nexus-webapp-nexusone

resources:
- ../../../../bases/nexus-webapp/1.0.0gw
- httproute.yaml

patches:
- path: secret.yaml
- path: deployment.yaml
