---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-api-deployment
  labels:
    app: nexus-api
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: nexus-api-container
        image: ghcr.io/synapsehealthtech/nexus-api:v0.2.6
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
