apiVersion: v1
kind: Service
metadata:
  name: nexus-backoffice-api-service
spec:
  type: ClusterIP
  selector:
    app: nexus-backoffice-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
