apiVersion: v1
data:
  ALGORITHM: SFMyNTY=
  DATABASE_URL: bXlzcWwrcHlteXNxbDovL2Rycl91c2VyOlVzZXJfcGFhYXNzd29yZF9zZWd1dXVyYSExQDEwLjAuODEuMjA0OjMzMDYvZHJyX25kYg==
  DB_PASSWORD: VXNlcl9wYXNzd29yZF9zZWd1cmEhMQ==
  DB_USER: dGVzdGVfdXNlcg==
  SECRET_KEY: dW1hLWNoYXZlLXNlY3JldGEtbXVpdG8tZm9ydGUtZS1kaWZpY2lsLWRlLWFkaXZpbmhhcg==
kind: Secret
metadata:
  name: nexus-db-credentials
type: Opaque
