apiVersion: v1
kind: Secret
metadata:
  name: auth-proxy-htpasswd
  namespace: debezium-platform
type: Opaque
stringData:
  .htpasswd: "admin@nexusplatform.com.br:$2b$12$D.tOillICuVYOkG8GTS7EeAzFRFLbksd1chno.T8wb3ar8cE1LLEa"
