apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-proxy
  namespace: debezium-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-proxy
  template:
    metadata:
      labels:
        app: auth-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
            - containerPort: 8081
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: htpasswd
              mountPath: /etc/nginx/.htpasswd
              subPath: .htpasswd
      volumes:
        - name: config
          configMap:
            name: auth-proxy-config
        - name: htpasswd
          secret:
            secretName: auth-proxy-htpasswd
