# Patch conductor para ambiente local (K3d)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conductor
spec:
  template:
    spec:
      containers:
        - name: conductor
          env:
            - name: QUARKUS_HTTP_CORS_ORIGINS
              value: "https://debezium-platform.tech.nexusplatform.com.br"
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://postgres.debezium-platform.svc.cluster.local:5432/debezium"
            - name: QUARKUS_KUBERNETES_CLIENT_NAMESPACE
              value: debezium-platform
