apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: debezium-platform

resources:
  - ../../../bases/debezium-platform/3.5
  - secret.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - httproute-conductor.yaml
  - httproute-stage.yaml
  - certificate.yaml
  - reference-grant.yaml

patches:
  - path: conductor-patch.yaml
  - path: stage-patch.yaml
