apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-gateway

resources:
- ../../../bases/nginx-gateway-fabric/2.4
- hpa-nginx-proxy.yaml

patches:
- path: nginx-proxy-patch.yaml
- path: deployment-patch.yaml
