apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus-agenticops

resources:
  - ../../../bases/nexus-agenticops/2.0.0
  - httproute-api.yaml
  - httproute-langfuse.yaml
  - httproute-litellm.yaml

patches:
  - path: configmap.yaml
  - path: litellm-configmap.yaml
  - path: secret.yaml
  - path: agents-api-deployment.yaml
  - path: arq-worker-deployment.yaml
  - path: minio-patch.yaml
  - path: postgres-pvc-patch.yaml
  - path: clickhouse-pvc-patch.yaml
  - path: hpa-patch.yaml
